// @ts-nocheck
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { describe, expect, it } from 'vitest'

const stylesDirectory = dirname(fileURLToPath(import.meta.url))
const baseStyles = readFileSync(join(stylesDirectory, 'styles.css'), 'utf8')
const detailStyles = readFileSync(join(stylesDirectory, 'styles/detail.css'), 'utf8')
const adminShellStyles = readFileSync(join(stylesDirectory, 'styles/admin-shell.css'), 'utf8')
const adminStyles = readFileSync(join(stylesDirectory, 'styles/admin.css'), 'utf8')
const styles = [baseStyles, detailStyles, adminShellStyles, adminStyles].join('\n')


describe('mobile latency target layout', () => {
  it('keeps latency target buttons readable as card tiles on phones', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.latency-target-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 6px; padding: 0 12px 12px; }')
    expect(styles).toContain('.latency-target-grid button')
    expect(styles).toContain('border-radius: var(--radius-field)')
    expect(styles).toContain('.latency-target-grid.is-loading button')
    expect(styles).toContain('.latency-panel-skeleton')
    expect(styles).toContain('.resource-chart-frame')
    expect(styles).toContain('grid-template-columns: 46px minmax(0, 1fr)')
    expect(styles).toContain('.latency-chart .axis-label { font-size: 10px; }')
  })
})

describe('mobile server detail layout', () => {
  it('stacks dense desktop detail facts into readable mobile rows', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.detail-hero__main { align-items: center; flex-direction: row; gap: 10px; }')
    expect(styles).toContain('.detail-fact-strip { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 6px; }')
    expect(styles).toContain('.detail-fact.is-wide { grid-column: 1 / -1; min-height: 54px; padding: 9px 11px; }')
    expect(styles).toContain('.detail-fact:not(.is-wide) strong { overflow: visible; text-overflow: clip; white-space: normal; overflow-wrap: anywhere; }')
    expect(styles).toContain('.monitor-heading { padding: 16px 14px 10px; flex-direction: row; align-items: flex-start; gap: 8px; }')
    expect(styles).toContain('.monitor-heading-actions { width: auto; flex: none; flex-wrap: nowrap; align-items: flex-start; justify-content: flex-end; margin-left: auto; }')
    expect(styles).toContain('.resource-history-header { padding: 16px 14px 10px; flex-direction: row; align-items: flex-start; gap: 8px; }')
    expect(styles).toContain('.resource-range-row { width: auto; flex: none; flex-wrap: nowrap; justify-content: flex-end; margin-left: auto; }')
  })
})

describe('route stylesheet boundaries', () => {
  it('keeps heavyweight admin workspace styles out of the public entry stylesheet', () => {
    expect(baseStyles).not.toContain('.admin-modal-backdrop')
    expect(baseStyles).not.toContain('.admin-server-sort-list')
    expect(adminShellStyles).toContain('.admin-login-card')
    expect(adminShellStyles).toContain('.admin-state-card')
    expect(adminShellStyles).not.toContain('.admin-modal-backdrop')
    expect(adminShellStyles).not.toContain('.admin-server-sort-list')
    expect(adminStyles).toContain('.admin-modal-backdrop')
    expect(adminStyles).toContain('.admin-server-sort-list')
    expect(adminStyles).toContain('@media (max-width: 767px)')
  })
})

describe('homepage and admin shell layout', () => {
  it('keeps homepage chrome and overview inside one shared card shell', () => {
    expect(styles).toContain('.home-top-card')
    expect(styles).toContain('.home-top-card .kulin-nav')
    expect(styles).toContain('.home-top-card .home-summary')
  })

  it('keeps route and admin workspace loading cards at one stable destination-aligned position', () => {
    expect(baseStyles).toContain('.route-state-container { display: flex; flex-direction: column; gap: 24px; }')
    expect(baseStyles).toMatch(/\.route-state-panel\s*\{[^}]*min-height: 180px;[^}]*display: flex;[^}]*flex-direction: column;[^}]*\}/)
    expect(baseStyles).toMatch(/\.route-state-card\s*\{[^}]*min-height: 96px;[^}]*margin-top: 18px;[^}]*display: flex;[^}]*gap: 10px;[^}]*padding: 18px 20px;[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--control-bg\);[^}]*\}/)
    expect(adminShellStyles).toMatch(/\.admin-state-card\s*\{[^}]*min-height: 96px;[^}]*margin-top: 18px;[^}]*display: flex;[^}]*gap: 10px;[^}]*padding: 18px 20px;[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--control-bg\);[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-state-card\s*\{[^}]*min-height: 96px;[^}]*margin-top: 18px;[^}]*display: flex;[^}]*gap: 10px;[^}]*padding: 18px 20px;[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--control-bg\);[^}]*\}/)
    expect(adminShellStyles).toContain('.admin-state-card { min-height: 84px; margin-top: 18px; padding: 16px; }')
    expect(adminStyles).toContain('.admin-state-card { min-height: 84px; margin-top: 18px; padding: 16px; }')
  })

  it('keeps the theme menu above later homepage sections', () => {
    expect(styles).toMatch(/\.home-top-card \{[^}]*position: relative;[^}]*z-index: 20;[^}]*overflow: visible;/)
    expect(styles).toMatch(/\.theme-menu-popover \{[^}]*z-index: 80;/)
  })

  it('does not leave touch-tapped header icon buttons in the desktop hover accent state', () => {
    expect(styles).toContain('@media (hover: hover) and (pointer: fine)')
    expect(styles).toContain('.nav-icon-button:hover:not(:disabled) { background: #eff6ff; color: var(--blue); transform: translateY(-1px); box-shadow: 0 6px 18px -14px var(--blue); }')
    expect(styles).toContain('.nav-icon-button:disabled { cursor: default; opacity: .45; }')
    expect(styles).toContain('.home-top-card .nav-icon-button:not(.is-solid):hover:not(:disabled)')
  })

  it('keeps mobile homepage server cards aligned to the top card width', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.kulin-node-card { max-width: none; min-height: 0; height: auto; }')
  })

  it('fits dedicated mobile backgrounds without cropping them against long page content', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.kulin-shell[data-background=\'on\']::before')
    expect(styles).toContain('var(--zeno-mobile-background-image, var(--zeno-desktop-background-image, none))')
    expect(styles).toContain('background-size: var(--zeno-mobile-background-size, cover)')
    expect(styles).toContain('box-shadow: inset 0 0 0 100vmax var(--zeno-background-overlay-color)')
    expect(styles).toContain('background-attachment: scroll')
  })

  it('uses one unboxed desktop row and a no-scroll mobile two-column summary', () => {
    expect(styles).toContain('.home-summary__metric')
    expect(styles).toContain('.home-summary__metric--status')
    expect(styles).toContain('.home-summary__metric--cost')
    expect(styles).toContain('.home-summary__status-dot')
    expect(styles).toContain('.home-summary__metric-label')
    expect(styles).toContain('.home-summary__metric-value')
    expect(styles).toContain('.home-summary__metric--upload')
    expect(styles).toContain('.home-summary__metric--download')
    expect(styles).toMatch(/\.home-top-card \.home-summary\s*\{[^}]*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\);[^}]*padding: 12px 0 0;[^}]*border-top: 1px solid color-mix\(in srgb, var\(--border\) 82%, transparent\);[^}]*\}/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*border: 1px solid var\(--border\)/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*background:/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*border-radius:/)
    expect(styles).toMatch(/\.home-summary__metric\s*\{[^}]*min-height: 40px;[^}]*align-items: center;[^}]*justify-content: center;[^}]*gap: 6px;[^}]*padding: 0 8px;[^}]*font-size: 12px;[^}]*font-weight: 400;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric \+ \.home-summary__metric\s*\{\s*box-shadow: inset 1px 0 var\(--border\);\s*\}/)
    expect(styles).not.toContain('.home-summary__tile')
    expect(styles).toContain('--summary-accent')
    expect(styles).toMatch(/\.home-summary__metric-label\s*\{[^}]*justify-content: flex-start;[^}]*gap: 5px;[^}]*flex: none;[^}]*font-size: inherit;[^}]*font-weight: inherit;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value\s*\{[^}]*flex: 0 1 auto;[^}]*justify-content: flex-start;[^}]*gap: 3px;[^}]*white-space: nowrap;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value strong\s*\{[^}]*font-size: inherit;[^}]*font-weight: inherit;[^}]*letter-spacing: 0;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value > span\s*\{[^}]*font-size: inherit;[^}]*font-weight: inherit;[^}]*\}/)
    expect(styles).toContain('.home-summary__metric--rate { gap: 2px; }')
    expect(styles).toContain('.home-summary__metric--rate > .home-summary__metric-label { width: calc(4em + 18px); }')
    expect(styles).toMatch(/\.home-summary__metric-value--rate\s*\{[^}]*gap: 4px;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value--rate > strong\s*\{[^}]*width: 5\.5ch;[^}]*text-align: right;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value--rate > span\s*\{[^}]*width: 4ch;[^}]*text-align: left;[^}]*\}/)
    expect(styles).toContain('.home-summary__metric-value--total strong { color: var(--summary-accent); }')
    expect(styles).not.toContain('.home-summary__metric-value--status strong')
    expect(styles).not.toContain('.home-summary__metric-value--cost strong')
    expect(styles).toContain('.home-currency-menu')
    expect(styles).toMatch(/\.home-currency-menu\s*\{[^}]*position: relative;[^}]*width: 52px;[^}]*height: 34px;[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-select\s*\{[^}]*display: inline-flex;[^}]*flex-wrap: nowrap;[^}]*justify-content: center;[^}]*white-space: nowrap;[^}]*\}/)
    expect(styles).not.toContain('.home-currency-select__flag')
    expect(styles).not.toContain('.home-currency-select svg')
    expect(styles).toMatch(/\.home-currency-select__value\s*\{[^}]*font-size: 14px;[^}]*font-weight: 500;[^}]*\}/)
    expect(styles).toContain('.home-currency-select:focus-visible')
    expect(styles).toContain('.home-currency-select[aria-expanded="true"]')
    expect(styles).toMatch(/\.home-currency-select\s*\{[^}]*transition:[^}]*transform 150ms ease;[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-select:hover,[\s\S]*?\.home-currency-select\[aria-expanded="true"\]\s*\{[^}]*transform: translateY\(-1px\);[^}]*\}/)
    expect(styles).not.toContain('.home-currency-select select')
    expect(styles).toContain('.home-currency-popover')
    expect(styles).not.toContain('.home-currency-popover__title')
    expect(styles).toMatch(/\.home-currency-popover\s*\{[^}]*right: 0;[^}]*left: auto;[^}]*transform-origin: top right;[^}]*\}/)
    expect(styles).toContain('.home-currency-popover { left: 50%; right: auto; transform: translateX(-50%); transform-origin: top center; }')
    expect(styles).toContain('.home-currency-option__flag')
    expect(styles).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(styles).toContain('background: var(--zeno-popover-bg)')
    expect(styles).toContain('backdrop-filter: blur(var(--zeno-popover-blur)) saturate(1.04)')
    expect(styles).toContain('.home-currency-popover button[data-active="true"]')
    expect(styles).toContain('border: 1px solid var(--border)')
    expect(styles).toContain('background: var(--surface-strong)')
    expect(styles).toContain('color-mix(in srgb, var(--blue) 48%, var(--border))')
    expect(styles).toMatch(/\.home-summary__metric-icon\s*\{[^}]*width: 13px;[^}]*height: 13px;[^}]*color: var\(--summary-accent, var\(--orange\)\);[^}]*\}/)
    expect(styles).toMatch(/\.node-head\s*\{[^}]*min-height: 24px;[^}]*grid-template-columns: 70px minmax\(0, 1fr\) 70px;[^}]*text-align: center;[^}]*\}/)
    expect(styles).toMatch(/\.node-os\s*\{[^}]*position: static;[^}]*grid-column: 1;[^}]*justify-self: start;[^}]*width: 20px;[^}]*height: 20px;[^}]*transform: none;[^}]*\}/)
    expect(styles).toMatch(/\.node-title-line\s*\{[^}]*grid-column: 2;[^}]*display: flex;[^}]*align-items: center;[^}]*justify-content: center;[^}]*gap: 4px;[^}]*\}/)
    expect(styles).toMatch(/\.node-uptime\s*\{[^}]*grid-column: 3;[^}]*justify-self: end;[^}]*color: var\(--green\);[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).not.toContain('.node-status-dot')
    expect(styles).not.toContain('.node-status.is-online')
    expect(styles).not.toContain('.node-status.is-offline')
    expect(styles).not.toContain('.node-title-line::after')
    expect(styles).not.toContain('.node-dot')
    expect(styles).not.toContain('.node-title-copy')
    expect(styles).not.toContain('.node-title-primary')
    expect(styles).not.toContain('.node-renewal-slot')
    expect(styles).not.toContain('.node-renewal-cost')
    expect(styles).not.toContain('.node-expiry-meta')
    expect(styles).toMatch(/\.node-specs\s*\{[^}]*margin-top: 12px;[^}]*grid-template-columns: repeat\(3, auto\);[^}]*justify-content: center;[^}]*gap: 12px;[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).toMatch(/\.node-spec svg\s*\{[^}]*width: 16px;[^}]*height: 16px;[^}]*\}/)
    expect(styles).toContain('.spec-cpu svg { color: #0ea5e9; }')
    expect(styles).toContain('.spec-memory svg { color: #10b981; }')
    expect(styles).toContain('.spec-disk svg { color: #8b5cf6; }')
    expect(styles).toMatch(/\.node-usage-grid\s*\{[^}]*grid-template-columns: minmax\(0, 1fr\);[^}]*gap: 14px;[^}]*\}/)
    expect(styles).toMatch(/\.usage-row\s*\{[^}]*display: flex;[^}]*gap: 6px;[^}]*padding: 0;[^}]*\}/)
    expect(styles).toMatch(/\.usage-track\s*\{[^}]*height: 10px;[^}]*\}/)
    expect(styles).not.toContain('.usage-row__detail')
    expect(styles).not.toContain('.usage-row__icon')
    expect(styles).toContain('.usage-row--cpu { --resource-accent: var(--blue); }')
    expect(styles).toContain('.usage-row--memory { --resource-accent: var(--green); }')
    expect(styles).toContain('.usage-row--disk { --resource-accent: var(--purple); }')
    expect(styles).toContain('.usage-row--traffic { --resource-accent: var(--orange); }')
    expect(styles).toMatch(/\.node-footer-grid\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[^}]*gap: 8px;[^}]*\}/)
    expect(styles).toMatch(/\.node-metric\s*\{[^}]*min-height: 40px;[^}]*flex-direction: row;[^}]*justify-content: space-between;[^}]*gap: 8px;[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--control-bg\);[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).not.toContain('.node-metric:nth-child(2n)')
    expect(styles).not.toContain('.node-metric:nth-child(n + 3)')
    expect(styles).toMatch(/\.server-card-list\s*\{[^}]*grid-auto-rows: auto;[^}]*align-items: start;[^}]*\}/)
    expect(styles).toMatch(/\.kulin-node-card\s*\{[^}]*min-height: 0;[^}]*height: auto;[^}]*\}/)
    expect(styles).toMatch(/\.node-usage\s*\{[^}]*margin-top: 20px;[^}]*flex: none;[^}]*align-content: start;[^}]*gap: 14px;[^}]*\}/)
    expect(styles).toMatch(/\.node-health-history\s*\{[^}]*display: grid;[^}]*gap: 8px;[^}]*\}/)
    expect(styles).toMatch(/\.node-health-metric\s*\{[^}]*min-height: 40px;[^}]*padding: 8px;[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--control-bg\);[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).not.toContain('.node-health-metric + .node-health-metric')
    expect(styles).toMatch(/\.history-cell\s*\{[^}]*height: 12px;[^}]*\}/)
    expect(styles).toMatch(/\.health-history-strip\s*\{[^}]*grid-template-columns: repeat\(12, minmax\(0, 1fr\)\);[^}]*\}/)
    expect(styles).toContain('.history-cell.is-good')
    expect(styles).toContain('.history-cell.is-warning')
    expect(styles).toContain('.history-cell.is-danger')
    expect(styles).toContain('.history-cell.is-empty')
    expect(styles).toContain('--billing-gold: #b8860b;')
    expect(styles).toContain('--billing-gold: #ffd45c;')
    expect(styles).toMatch(/\.metric-expiry\.is-safe\s*\{\s*--metric-accent: var\(--green\);\s*\}/)
    expect(styles).toMatch(/\.metric-expiry\.is-soon\s*\{\s*--metric-accent: var\(--orange\);\s*\}/)
    expect(styles).toMatch(/\.metric-expiry\.is-urgent,\s*\.metric-expiry\.is-expired\s*\{\s*--metric-accent: var\(--red\);\s*\}/)
    expect(styles).toContain('.metric-billing { --metric-accent: var(--billing-gold); }')
    expect(styles).toMatch(/\.home-summary__status-dot\s*\{[^}]*width: 6px;[^}]*height: 6px;[^}]*background: var\(--green\);[^}]*\}/)
    expect(styles).toMatch(/\.home-top-card \.home-summary\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[^}]*row-gap: 2px;[^}]*padding-top: 10px;[^}]*overflow: hidden;[^}]*\}/)
    expect(styles).not.toContain('.home-top-card .home-summary::-webkit-scrollbar')
    expect(styles).toContain('.home-summary__metric + .home-summary__metric { box-shadow: none; }')
    expect(styles).toContain('.home-summary__metric:nth-child(2n) { box-shadow: inset 1px 0 var(--border); }')
    expect(styles).toContain('.home-summary__metric:nth-child(n + 3) { box-shadow: inset 0 1px var(--border); }')
    expect(styles).toContain('.home-summary__metric:nth-child(2n):nth-child(n + 3) { box-shadow: inset 1px 0 var(--border), inset 0 1px var(--border); }')
    expect(styles).toMatch(/\.home-summary__metric\s*\{\s*min-height: 34px; gap: 5px; padding: 0 4px;\s*\}/)
    expect(styles).toContain('.home-summary__metric-value--rate { gap: 4px; }')
    expect(styles).toContain('@media (max-width: 360px)')
    expect(styles).toContain('.home-summary__metric { gap: 3px; padding: 0 2px; font-size: 11px; }')
    expect(styles).toContain('.home-summary__metric--rate { gap: 2px; padding-inline: 1px; }')
    expect(styles).toContain('.home-summary__metric--rate > .home-summary__metric-label { width: calc(4em + 13px); }')
    expect(styles).toContain('.home-summary__metric--rate .home-summary__metric-value { gap: 3px; }')
    expect(styles).toContain('.home-currency-menu { width: 50px; height: 32px; flex-basis: 50px; }')
    expect(styles).toContain('.home-currency-select__value { font-size: 12px; font-weight: 500; }')
    expect(styles).not.toContain('.home-summary__status-body')
    expect(styles).not.toContain('.home-summary__status-cost')
    expect(styles).not.toContain('.home-summary__snapshot')
    expect(styles).not.toContain('.home-summary__network-board')
    expect(styles).not.toContain('.home-summary__status-track')
    expect(styles).not.toContain('--gold:')
    expect(styles).toContain('font-weight: 400')
    expect(styles).not.toContain('.home-summary__compact')
  })

  it('keeps general popovers unified and admin secondary popovers on the appearance-controlled surface', () => {
    expect(styles).toContain(':root[data-zeno-theme="light"]')
    expect(styles).toContain(':root[data-zeno-theme="dark"]')
    expect(styles).toMatch(/:root\[data-zeno-theme="light"\]\s*\{[^}]*color-scheme: light;/)
    expect(styles).toMatch(/:root\[data-zeno-theme="dark"\]\s*\{[^}]*color-scheme: dark;/)
    expect(styles).toContain('--zeno-popover-bg: var(--surface-strong)')
    expect(styles).toContain('--zeno-popover-blur: 18px')
    expect(styles).toMatch(/\.theme-menu-popover\s*\{[^}]*background: var\(--zeno-popover-bg\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-popover\s*\{[^}]*background: var\(--zeno-popover-bg\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-select-popover\s*\{[^}]*--zeno-popover-blur: var\(--zeno-card-blur\);[^}]*background: var\(--admin-secondary-surface\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-date-popover\s*\{[^}]*--zeno-popover-blur: var\(--zeno-card-blur\);[^}]*background: var\(--admin-secondary-surface\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-date-option-panel\s*\{[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(styles).toMatch(/\.admin-expanded-checklist__list\s*\{[^}]*background: var\(--zeno-popover-bg\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-install-platforms\s*\{[^}]*--zeno-popover-blur: var\(--zeno-card-blur\);[^}]*background: var\(--admin-secondary-surface\);[^}]*backdrop-filter: blur\(var\(--zeno-popover-blur\)\) saturate\(1\.04\);[^}]*\}/)
  })

  it('styles the backend/admin shell with the same translucent card language as the front page', () => {
    expect(styles).toContain('.admin-panel')
    expect(styles).toContain('.admin-workspace-panel .admin-list')
    expect(styles).toContain('--surface-strong')
    expect(styles).toContain('background: var(--surface-strong)')
    expect(styles).toContain('--zeno-card-blur')
    expect(styles).toContain('backdrop-filter: blur(var(--zeno-card-blur))')
    expect(styles).not.toContain('saturate(1.14)')
  })

  it('keeps the homepage backend entry visible on phones', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.login-link,')
    expect(styles).toContain('.nav-logout-button')
    expect(styles).toContain('min-height: 32px')
    expect(styles).not.toContain('.login-link { display: none; }')
  })

  it('polishes backend mobile navigation, modal actions, and save buttons without overlap', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.admin-section-nav {')
    expect(styles).toContain('grid-template-columns: repeat(5, minmax(0, 1fr))')
    expect(styles).toContain('overflow: hidden')
    expect(styles).toContain('.admin-section-nav button { min-width: 0; min-height: 38px; padding: 0 5px; border-radius: var(--radius-field); }')
    expect(styles).not.toContain('.admin-section-icon')
    expect(styles).not.toContain('scroll-snap-type: x proximity')
    expect(styles).toContain('.admin-modal { width: 100%; height: min(92dvh, 760px); max-height: calc(100dvh - 16px); border-radius: var(--radius-panel); padding: 0; }')
    expect(styles).toContain('.admin-modal-actions {')
    expect(styles).toContain('position: sticky')
    expect(styles).toContain('bottom: 0')
    expect(styles).toContain('max(10px, env(safe-area-inset-bottom))')
    expect(styles).toContain('.admin-settings-form > button[type="submit"] { width: 100%; margin-top: 14px; }')
    expect(styles).toContain('.admin-alert-rule-add-form .admin-rule-picker { margin-top: 0; }')
    expect(styles).toContain('.admin-node-edit-form button.admin-primary-action')
    expect(styles).toContain('.admin-section-heading h3 { white-space: nowrap; font-size: 22px; }')
    expect(styles).toContain('.admin-section-actions { width: auto; flex: 0 0 auto; margin-left: auto; justify-content: flex-end; flex-wrap: nowrap; gap: 6px; }')
    expect(styles).toContain('.admin-block-heading .admin-primary-action { height: 34px; padding: 0 10px; font-size: 12px; }')
    expect(styles).toContain('.admin-target-assignment-list,')
    expect(styles).toContain('.admin-notification-list .admin-row-actions.admin-icon-actions,')
  })

  it('keeps destructive confirmations compact, stable, and touch-friendly', () => {
    expect(styles).toContain('.admin-modal.admin-delete-modal')
    expect(styles).toContain('width: min(480px, 100%)')
    expect(styles).toContain('.admin-delete-confirm__lead')
    expect(styles).toContain('.admin-delete-confirm__hint')
    expect(styles).not.toContain('.admin-delete-subject')
    expect(styles).not.toContain('.admin-delete-impact')
    expect(styles).toContain('.admin-delete-feedback')
    expect(styles).toContain('min-height: 38px')
    expect(styles).toContain('max-height: 72px')
    expect(styles).toContain('.admin-delete-feedback.is-error')
    expect(styles).toContain('.admin-modal.admin-delete-modal { height: auto; max-height: calc(100dvh - 16px); }')
    expect(styles).toContain('.admin-delete-modal .admin-modal-close { width: 44px; height: 44px; flex: 0 0 44px; }')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 1.15fr)')
    expect(styles).toContain('min-height: 46px')
  })

  it('keeps authenticated node management in compact lists without old card shells', () => {
    expect(styles).toContain('.admin-login-card')
    expect(styles).toContain('width: min(100%, 440px)')
    expect(styles).toContain('grid-template-columns: 1fr')
    expect(styles).toContain('.admin-login-title { padding-bottom: 2px; text-align: center; }')
    expect(styles).toContain('.brand-logo-fallback')
    expect(styles).toContain('border-radius: 50%')
    expect(styles).toContain('gap: 20px')
    expect(styles).toContain('padding: 26px 24px')
    expect(styles).not.toContain('grid-template-columns: minmax(0, 1fr) minmax(140px, 220px)')
    expect(styles).toContain('.admin-node-section')
    expect(styles).toContain(".admin-section-nav button[data-active='true']")
    expect(styles).toContain('.admin-node-status')
    expect(styles).toContain('.admin-status-indicator.status-online .admin-status-dot')
    expect(styles).toContain('.admin-server-sort-list')
    expect(styles).toContain('.admin-server-sort-item')
    expect(styles).toContain('cursor: grab')
    expect(styles).not.toContain('.admin-node-card')
    expect(styles).not.toContain('.admin-target-card')
    expect(styles).not.toContain('.admin-node-grid')
  })

  it('lets admin lists size to content without internal scroll containers', () => {
    expect(styles).toContain('.admin-workspace-panel .admin-list')
    expect(styles).toContain('max-height: none')
    expect(styles).toContain('overflow: visible')
    expect(styles).toContain('scrollbar-gutter: auto')
    expect(styles).toContain('padding: 10px 12px')
    expect(styles).toContain('min-height: 64px')
    expect(styles).toContain('.admin-ip-stack')
    expect(styles).toContain('height: 34px')
    expect(styles).toContain('repeat(auto-fit, minmax(96px, 1fr))')
    expect(styles).toContain('.admin-node-section .admin-list-row,')
    expect(styles).toContain('.admin-target-list .admin-list-row,')
    expect(styles).toContain('overflow-wrap: anywhere')
    expect(styles).not.toContain('max-height: calc(100dvh - 300px)')
    expect(styles).not.toContain('max-height: calc(100dvh - 260px)')
    expect(styles).not.toContain('.overview-card')
    expect(styles).not.toContain('.server-overview')
  })

  it('simplifies backend chrome and gives secondary forms card-aligned sections', () => {
    expect(styles).toContain('background: transparent')
    expect(styles).toContain('box-shadow: none')
    expect(styles).toContain('font-size: 23px')
    expect(styles).toContain('font-size: 15px')
    expect(styles).toContain('.admin-account-section,')
    expect(styles).toContain('.admin-form-section')
    expect(styles).toContain('.admin-form-section-title::before')
    expect(styles).toContain('border-radius: var(--radius-card)')
    expect(styles).toContain('.admin-segmented-options')
    expect(styles).toMatch(/\.admin-select-popover\s*\{[^}]*overflow: auto;[^}]*border-radius: var\(--radius-card\);[^}]*clip-path: inset\(0 round var\(--radius-card\)\);[^}]*\}/)
    expect(styles).toContain('.admin-modal-body')
    expect(styles).toContain('clip-path: inset(0 round var(--radius-panel))')
    expect(styles).not.toContain('--admin-modal-section-bg')
    expect(styles).not.toContain('--admin-modal-control-bg')
    expect(styles).not.toContain('--admin-modal-action-bg')
    expect(styles).toContain('--admin-secondary-surface: #ffffff')
    expect(styles).toMatch(/\.admin-modal\s*\{[^}]*--surface-strong: transparent;[^}]*--field-bg: transparent;[^}]*--zeno-popover-bg: transparent;[^}]*--zeno-popover-blur: 0px;[^}]*background: var\(--admin-secondary-surface\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-form-section\s*\{[^}]*background: var\(--surface-soft\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-node-edit-form input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\),[\s\S]*?background: var\(--field-bg\);/)
    expect(styles).toContain('.admin-notification-list .admin-node-status')
    expect(styles).toContain('.admin-install-copy-menu')
    expect(styles).toContain('.admin-install-copy-button')
    expect(styles).toContain('.admin-install-copy-row { flex-wrap: nowrap; gap: 10px; }')
    expect(styles).toContain('.admin-inline-note')
    expect(styles).toMatch(/\.admin-install-platforms\s*\{[^}]*position: fixed;/)
    expect(styles).not.toContain('scroll-margin: 96px 0')
    expect(styles).not.toContain('.admin-install-command')
  })
})

describe('state history layout', () => {
  it('keeps the detail hero dense with Nezha-like inline facts, not nested metric cards', () => {
    expect(styles).toContain('.detail-fact-strip')
    expect(styles).toContain('.detail-status-pill')
    expect(styles).toContain('.detail-fact.is-wide')
    expect(styles).toContain('border-top: 1px solid color-mix(in srgb, var(--border) 82%, transparent)')
    expect(styles).not.toContain('.detail-hero,\n.latency-panel,')
    expect(styles).not.toContain('.detail-info-card')
  })

  it('renders resource history as a compact chart grid like Kulin on desktop', () => {
    expect(styles).toContain('.resource-history-grid')
    expect(styles).toContain('grid-template-columns: repeat(auto-fit, minmax(290px, 1fr))')
    expect(styles).toContain('grid-template-columns: 1fr')
    expect(styles).toContain('.resource-card')
    expect(styles).toContain('background: var(--surface)')
    expect(styles).toContain('.resource-card,')
    expect(styles).toContain('box-shadow: var(--zeno-card-shadow)')
    expect(styles).toContain('.resource-y-axis')
    expect(styles).toContain('.resource-chart-plot')
    expect(styles).toContain('.resource-x-axis')
    expect(styles).toContain('.resource-chart-area { opacity: .2; stroke: none; pointer-events: none; }')
    expect(styles).toContain('.resource-card-header')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr) auto')
  })

  it('keeps only the server status as a compact pill in the top server card', () => {
    expect(styles).toContain('.detail-hero__badges')
    expect(styles).toContain('border-radius: var(--radius-pill)')
  })

  it('freezes offline homepage cards by dimming colored content without grayscale', () => {
    expect(styles).toMatch(/\.kulin-node-card\.is-offline \.node-head,[\s\S]*?\.node-usage \{[^}]*opacity: \.56;[^}]*\}/)
    expect(styles).toMatch(/\.node-offline-watermark\s*\{[^}]*position: absolute;[^}]*z-index: 2;[^}]*pointer-events: none;[^}]*transform: rotate\(-24deg\);[^}]*color: color-mix\(in srgb, var\(--red\) 24%, transparent\);[^}]*font-size: 52px;[^}]*\}/)
    // Offline cards must never grayscale or tint the card surface (2026-07-05 decision).
    expect(styles).not.toContain('filter: grayscale')
    expect(styles).not.toMatch(/\.kulin-node-card\.is-offline\s*\{/)
    expect(styles).not.toContain('.kulin-node-card.is-offline::before')
  })

  it('keeps server-card usage tracks visible on white cards', () => {
    expect(styles).toContain('--usage-track-bg')
    expect(styles).toContain('--usage-track-border')
    expect(styles).toContain('background: var(--usage-track-bg)')
    expect(styles).toContain('.usage-track { position: relative; width: 100%; height: 10px; overflow: hidden; border: 0;')
  })
})

describe('Kulin-inspired color polish', () => {
  it('keeps the overall shell and cards pure white instead of aurora/grey backgrounds', () => {
    expect(styles).toContain('--background: #ffffff')
    expect(styles).toContain('--card: #ffffff')
    expect(styles).toContain('background-image: var(--zeno-desktop-background-image, none)')
    expect(styles).not.toContain('--zeno-glow-primary')
    expect(styles).not.toContain('radial-gradient(circle at')
    expect(styles).not.toContain('linear-gradient(135deg, var(--zeno-bg-a)')
  })

  it('uses solid accent colors without gradients and keeps key identity emphasized', () => {
    expect(styles).toContain('.home-summary__metric-value strong')
    expect(styles).toContain('.home-summary__metric-value > span')
    expect(styles).toContain('.home-summary__metric-value--rate > span')
    expect(styles).toContain('.metric-label { min-width: 0; overflow: hidden; color: var(--metric-accent)')
    expect(styles).toContain('.node-title-line p { max-width: calc(100% - 23px); min-width: 0; flex: none; margin: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--foreground); font-size: 13px; font-weight: 600')
    expect(styles).toContain('.detail-title-button span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 600; }')
    expect(styles).toContain('.node-metric strong')
    expect(styles).toContain('.node-metric strong { max-width: 100%; min-width: 0; flex: 1; overflow: hidden; color: var(--metric-accent); font-size: 11px; font-weight: 500; line-height: 1.15; text-align: right; text-overflow: ellipsis; white-space: nowrap;')
    expect(styles).toContain('.metric-billing { --metric-accent: var(--billing-gold); }')
    expect(styles).toContain('.node-health-metric {')
    expect(styles).toContain('--metric-accent: var(--green);')
    expect(styles).toContain('.node-health-metric.health-loss { --metric-accent: var(--orange); }')
    expect(styles).not.toContain('.metric-latency')
    expect(styles).toContain('.latency-target-grid strong { color: var(--foreground); font-size: 20px')
    expect(styles).toContain('font-weight: 600; letter-spacing: -0.03em')
    expect(styles).toContain('.latency-monitor-heading .monitor-title-row h3 { font-weight: 600; }')
    expect(styles).toContain('.home-summary__metric-value--total strong')
    expect(styles).toContain('font-size: inherit')
    expect(styles).toContain('font-weight: inherit')
    expect(styles.match(/font-weight: 600/g)?.length ?? 0).toBeGreaterThanOrEqual(4)
    expect(styles).toContain('.latency-target-grid em { color: var(--muted)')
    expect(styles).toContain('.admin-section-nav button[data-active=\'true\']')
    expect(styles).not.toContain('.admin-section-icon')
    expect(styles).toContain('background: var(--blue)')
    expect(styles).toContain('.resource-card.tone-green')
    expect(styles).toContain('.resource-chart-tooltip')
    expect(styles).toContain('.server-flag__image')
    expect(styles).toMatch(/\.region-filter-buttons \.server-flag \{[^}]*font-size: 16px;[^}]*\}/)
    expect(styles).not.toMatch(/\.region-filter-buttons \.server-flag \{[^}]*(?:border|box-shadow|overflow)[^}]*\}/)
    expect(styles).toContain('.latency-chart-tooltip foreignObject')
    expect(styles).toContain('.latency-tooltip-card')
    expect(styles).not.toContain('<title>')
    expect(styles).not.toContain('.resource-card::before')
    expect(styles).not.toContain('--zeno-accent-gradient')
    expect(styles).not.toContain('linear-gradient')
    expect(styles).not.toContain('radial-gradient')
  })
})

describe('visual weight polish', () => {
  it('avoids heavy UI font weights in the Nezha-like shell', () => {
    expect(styles).not.toContain('font-weight: 650')
    expect(styles).not.toContain('font-weight: 700')
    expect(styles).not.toContain('font-weight: 750')
    expect(styles).not.toContain('font-weight: 760')
    expect(styles).not.toContain('font-weight: 780')
  })

  it('keeps custom icon strokes and resource curves lighter than the default heavy Lucide stroke', () => {
    expect(styles).toContain('stroke-width: 1.75')
    expect(styles).toContain('.detail-title-button svg')
    expect(styles).toContain('stroke-width: 1.6')
    expect(styles).toContain('.resource-chart-line { fill: none; stroke-width: 1.55')
  })
})
